app/inspires/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, URL, NumberRange, AnyOf
from app.main import SELECT_ACTIVITIES, VALID_ACTIVITIES


class InspiresForm(FlaskForm):
    title = StringField('Title *', validators=[DataRequired(), Length(min=0, max=50)])
    url = StringField('Web Link *', validators=[DataRequired(), URL()])
    instructor = StringField('Name of Instructor (optional)', validators=[Length(min=0, max=50)])
    duration = IntegerField('Typical Duration (mins) *',
                            validators=[DataRequired(),
                                        NumberRange(0, 120, message="Please enter a number between 0 and 120")])
    type = SelectField('Type *', choices=SELECT_ACTIVITIES, validators=[AnyOf(VALID_ACTIVITIES)])
    description = TextAreaField('Description *', validators=[DataRequired(), Length(min=0, max=200)])
    why_inspires = TextAreaField('Why does it inspire me *', validators=[DataRequired(), Length(min=0, max=200)])

    submit = SubmitField('Save')

app/inspires/__init__.py
from flask import Blueprint

bp = Blueprint('inspires', __name__)

from app.inspires import routes, forms

app/inspires/routes.py
from datetime import datetime

from flask import render_template, flash, redirect, url_for
from flask_login import current_user, login_required

from app import db
from app.inspires import bp
from app.inspires.forms import InspiresForm
from app.main import ICONS_LOOKUP
from app.models import Inspiration, MyInspirationLikes
from app.services.charting import ACTIVITY_COLOR_LOOKUP
from app.main import ACTIVITIES_LOOKUP


@bp.route('/inspires_list', methods=['GET'])
@login_required
def view_inspirations():
    """
    Shows the list of inspirations from others
    :return:
    :rtype:
    """
    inspirations = Inspiration.query.all()
    return render_template('inspires/inspirations.html', title='Inspire others', inspirations=inspirations,
                           icons=ICONS_LOOKUP, colors=ACTIVITY_COLOR_LOOKUP)


@bp.route('/detail_inspiration/<int:inspiration_id>', methods=['GET'])
@login_required
def detail_inspiration(inspiration_id):
    """
    Shows the details of a specific inspiration
    :param inspiration_id: inspiration to view
    :type inspiration_id: int
    :return:
    :rtype:
    """
    inspiration = Inspiration.query.filter_by(id=inspiration_id).first_or_404()
    return render_template('inspires/detail_inspiration.html', title='Inspire others', inspiration=inspiration,
                           icons=ICONS_LOOKUP,  colors=ACTIVITY_COLOR_LOOKUP, activity_map=ACTIVITIES_LOOKUP)


@bp.route('/add_inspiration', methods=['GET', 'POST'])
@login_required
def add_inspiration():
    """
    creates a new inspiration
    :return:
    :rtype:
    """
    form = InspiresForm()
    if form.validate_on_submit():
        inspiration = Inspiration(title=form.title.data,
                                  description=form.description.data,
                                  why_loved=form.why_inspires.data,
                                  duration=form.duration.data,
                                  instructor=form.instructor.data,
                                  url=form.url.data,
                                  workout_type=int(form.type.data),
                                  likes=1,
                                  instructor_sex=0,
                                  user_id=current_user.get_id())
        db.session.add(inspiration)
        likes_inspiration = MyInspirationLikes(user_id=current_user.get_id(), inspiration_id=inspiration.id)
        db.session.add(likes_inspiration)
        db.session.commit()
        flash('Thank you for sharing your inspiration')
        return redirect(url_for('inspires.view_inspirations'))

    return render_template('inspires/edit_inspiration.html', title='Inspire others', form=form,
                           is_add_inspiration=True)


@bp.route('/edit_inspiration/<int:inspiration_id>', methods=['GET', 'POST'])
@login_required
def edit_inspiration(inspiration_id):
    """
    edits an existing inspiration
    only the user who created it can edit it
    :param inspiration_id: inspiration to edit
    :type inspiration_id: int
    :return:
    :rtype:
    """
    inspiration = Inspiration.query.filter_by(user_id=current_user.get_id(), id=inspiration_id).first_or_404()
    form = InspiresForm(obj=inspiration)
    if form.validate_on_submit():
        inspiration.title = form.title.data
        inspiration.description = form.description.data
        inspiration.why_loved = form.why_inspires.data
        inspiration.duration = form.duration.data
        inspiration.instructor = form.instructor.data
        inspiration.url = form.url.data
        inspiration.workout_type = int(form.type.data)
        inspiration.last_updated = datetime.utcnow()
        db.session.commit()
        flash('Saved changes to the inspiration {}'.format(inspiration.title))
        return redirect(url_for('inspires.view_inspirations'))

    form.title.data = inspiration.title
    form.description.data = inspiration.description
    form.why_inspires.data = inspiration.why_loved
    form.duration.data = inspiration.duration
    form.instructor.data = inspiration.instructor
    form.url.data = inspiration.url
    form.type.data = inspiration.workout_type
    return render_template('inspires/edit_inspiration.html', title='Inspire others', form=form,
                           is_add_inspiration=False)


@bp.route('/delete_inspiration/<int:inspiration_id>', methods=['GET'])
@login_required
def delete_inspiration(inspiration_id):
    """
    deletes an existing inspiration
    only the user who created it can delete it
    :param inspiration_id: inspiration to delete
    :type inspiration_id: int
    :return:
    :rtype:
    """
    inspiration = Inspiration.query.filter_by(user_id=current_user.get_id(), id=inspiration_id).first_or_404()
    inspiration_title = inspiration.title
    db.session.delete(inspiration)
    db.session.commit()
    flash('Deleted inspiration {}'.format(inspiration_title))

    return redirect(url_for('inspires.view_inspirations'))


@bp.route('/like_inspiration/<int:inspiration_id>', methods=['GET'])
@login_required
def like_inspiration(inspiration_id):
    """
    likes an inspiration. A user cannot like an inspiration they've created
    :param inspiration_id: inspiration to like
    :type inspiration_id:
    :return:
    :rtype:
    """
    inspiration = Inspiration.query.filter_by(id=inspiration_id).first_or_404()

    # check to see if user has liked this previously
    has_liked_before = MyInspirationLikes.query.filter_by(id=inspiration_id, user_id=current_user.get_id()).count()
    if has_liked_before == 0:
        inspiration.likes += 1
        inspiration.last_updated = datetime.utcnow()
        likes_inspiration = MyInspirationLikes(user_id=current_user.get_id(), inspiration_id=inspiration_id)
        db.session.add(likes_inspiration)
        db.session.commit()

    return redirect(url_for('inspires.view_inspirations'))

app/templates/inspires/detail_inspiration.html
{% from "macros.html" import add_disqus with context %}
{% extends "base.html" %}

{% block content %}

    <div class="row">
        <div class="col-md-8 mx-auto">
            <h4 class="h4 mb-3 font-weight-normal">Be inspired</h4>
            <p>This is what our community says about this workout.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h5 class="h5 mb-3 font-weight-normal"><i class="{{ icons[inspiration.workout_type] }}"
                                                      aria-hidden=true></i>&nbsp;{{ inspiration.title }}
                lasts {{ inspiration.duration }} mins.
                {% if inspiration.instructor %}
                    &nbsp;with
                    instructor {{ inspiration.instructor }}
                {% endif %}
            </h5>
        </div>
    </div>
    {% if inspiration.meta_og_image %}
        <div class="row justify-content-center">
            <div class="col-md-2 bg-light">
                <img src="{{ inspiration.meta_og_image }}" alt="Meta image" width="100px">
            </div>
            <div class="col-md-6 bg-light">
                <p>{{ inspiration.meta_og_description }}</p>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-8 mx-auto">
            <p>And what does our community say?</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mx-auto">
            <blockquote><p class="mb-0">{{ inspiration.description }}</p>
                <footer class="blockquote-footer">Check it out at <a href="{{ inspiration.url }}"
                                                                     target="_blank">{{ inspiration.url }}</a></footer>
            </blockquote>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mx-auto">
            Why does it inspire?
            {{ inspiration.why_loved }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mx-auto">
            {% if inspiration.user_id == current_user.id %}
                <a id="edit_inspiration_link"
                   href="{{ url_for('inspires.edit_inspiration',inspiration_id=inspiration.id) }}"><i
                        class="fas fa-edit" aria-hidden="true"></i></a>
                &nbsp;&nbsp;&nbsp;
                <a id="delete_inspiration_link"
                   href="{{ url_for('inspires.delete_inspiration',inspiration_id=inspiration.id) }}"><i
                        class="fas fa-trash" aria-hidden="true"></i></a>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div id="disqus_thread"></div>
            {%- set disqus_identifier -%}
            {{ "{}_{}".format('inspires', inspiration.id) }}
            {%- endset -%}
            {%- set disqus_title -%}
            {{ "{} a {}-{}".format('be inspired by ', activity_map[inspiration.workout_type], inspiration.title) }}
            {%- endset -%}
            {% set disqus_url | get_os_env('DISQUS_URL') %}
            {% endset %}
            {{ add_disqus(disqus_identifier, disqus_title, disqus_url) }}
        </div>
    </div>
{% endblock %}

app/templates/inspires/edit_inspiration.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h1 class="h3 mb-3 font-weight-normal">Share Your Inspirations</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mx-auto bg-light">
            <p>Are there online shows or live/recorded classes that you follow? Do they inspire you? If so, please share so our
                community can also be inspired.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mx-auto box-shadow bg-light">
            <h3 class="h3 mb-3 font-weight-normal">My Inspiration</h3>
            <form action="" method="post" novalidate>
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ wtf.form_field(form.title, class="form-control") }}
                    {% for error in form.title.errors %}
                        <small class="form-text text-muted">[{{ error }}]</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ wtf.form_field(form.url, class="form-control") }}
                    {% for error in form.url.errors %}
                        <small class="form-text text-muted">[{{ error }}]</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ wtf.form_field(form.instructor, class="form-control") }}
                    {% for error in form.instructor.errors %}
                        <small class="form-text text-muted">[{{ error }}]</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ wtf.form_field(form.duration, class="form-control") }}
                    {% for error in form.duration.errors %}
                        <small class="form-text text-muted">[{{ error }}]</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ wtf.form_field(form.type, class="form-control") }}
                    {% for error in form.type.errors %}
                        <small class="form-text text-muted">[{{ error }}]</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ wtf.form_field(form.description, class="form-control") }}
                    {% for error in form.description.errors %}
                        <small class="form-text text-muted">[{{ error }}]</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ wtf.form_field(form.why_inspires, class="form-control") }}
                    {% for error in form.why_inspires.errors %}
                        <small class="form-text text-muted">[{{ error }}]</small>
                    {% endfor %}
                </div>
                <div class="text-right">
                    <a href="{{ url_for('main.exercise_log') }}" class="btn btn-secondary">Cancel</a>
                    <button id="submit" class="btn btn-primary" type="submit">Inspire Others!</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/inspires/inspirations.html
{% extends "base.html" %}

{% block content %}


    <div class="row">
        <div class="col-md-8 mx-auto">
            <h4 class="h4 mb-3 font-weight-normal">Be inspired</h4>
            <p>Here are some online workouts and guided exercises that our community recommends.</p>
        </div>
    </div>
    {% if inspirations %}
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="card-columns">
                    {% for inspiration in inspirations %}
                        <div class="card mb-3 border-0" style="background-color: {{ colors[inspiration.workout_type] }}">
                        {% if inspiration.meta_og_image %}
                            <img class="card-img-top" src="{{ inspiration.meta_og_image }}" alt="Image from workout">
                        {%  endif %}
                            <div class="card-body">
                                <h5 class="card-text"><i class="{{ icons[inspiration.workout_type] }}"
                                                         aria-hidden=true></i>&nbsp;{{ inspiration.title }}</h5>
                            </div>
                            <div class="card-footer">
                                {{ inspiration.duration }} mins.
                                <a id="detail_link" href="{{ url_for('inspires.detail_inspiration',inspiration_id=inspiration.id) }}"><i
                                        class="fas fa-info-circle" aria-hidden="true"></i></a>
                                <a href="{{ inspiration.url }}" target="_blank">View&nbsp;<i
                                        class="fas fa-external-link-alt" aria-hidden=true></i></a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-8 mx-auto">
            <p id="no_reg"> Have an exercise that inspires you. Please <a id="set_up"
                                                                          href="{{ url_for('inspires.add_inspiration') }}">share
                with our community</a>.</p>
        </div>
    </div>

{% endblock %}